export interface HomeSeed {
  key: string;
  group: "team" | "reviews" | "facility" | "approach";
  heading: string;
  eyebrow: string;
  body: string;
  imageUrl: string;
}

export const homepageSeeds: HomeSeed[] = [
  { key: "team-madhav", group: "team", heading: "Mr. Madhav Singh", eyebrow: "Founder of Roar Wellness", body: "Founder of ROAR, involved full time with therapeutic and facility management. He has worked for over 14 years to help people recover and live alcohol- and drug-free lives.", imageUrl: "https://www.roarwellness.org/wp-content/uploads/2025/05/111383828753madhav-1.jpg" },
  { key: "team-manish", group: "team", heading: "Dr. Manish Sarkar", eyebrow: "Director of Roar Wellness", body: "A renowned psychiatrist of Delhi NCR with over two decades of experience in psychiatric disorders and substance dependence, with postgraduate training from NIMHANS, Bangalore.", imageUrl: "https://www.roarwellness.org/wp-content/uploads/2025/05/736893036507dr-manish-sarkar-1.jpg" },
  { key: "team-dhruv", group: "team", heading: "Dhruv Singh Tanwar", eyebrow: "Director of Roar Wellness", body: "A young, energetic director and social activist who volunteers with youth and social development programs and shares the knowledge gained from his journey.", imageUrl: "https://www.roarwellness.org/wp-content/uploads/2025/05/880816739116Dhruv-Singh-Tanwa-1.jpg" },
  { key: "review-sumit", group: "reviews", heading: "Sumit Kumar", eyebrow: "Client review", body: "If you're serious about recovery, RoarWellness is the place to go! Incredible staff, great facilities, and real results.", imageUrl: "https://i.pravatar.cc/96?img=12" },
  { key: "review-suraj", group: "reviews", heading: "Suraj Kumar", eyebrow: "Client review", body: "Best rehab centre in Delhi I ever visited. My friend Ravi Kumar recovered from alcohol addiction from here after suffering for 19 years.", imageUrl: "https://i.pravatar.cc/96?img=13" },
  { key: "review-neha", group: "reviews", heading: "Neha Jha", eyebrow: "Client review", body: "One of the best rehab centre in Delhi I must say. My brother recovered from alcohol addiction from Roar Wellness. Thanks to Dhruv sir and the Roar Wellness team.", imageUrl: "https://i.pravatar.cc/96?img=47" },
  { key: "review-yosika", group: "reviews", heading: "Yosika Patel", eyebrow: "Client review", body: "Thanks to Mr. Dhruv sir and his team for supporting us. My brother is happy now after treatment of alcohol addiction.", imageUrl: "https://i.pravatar.cc/96?img=32" },
  { key: "review-empirecraft", group: "reviews", heading: "EmpireCraft Limos", eyebrow: "Client review", body: "I must say that Roar Wellness Rehab Centre is one of the best luxury rehab centres for alcohol in Delhi. Thanks for the great service.", imageUrl: "https://i.pravatar.cc/96?img=68" },
  { key: "review-rohit", group: "reviews", heading: "Rohit Yadav", eyebrow: "Client review", body: "A supportive and professional rehab center! The therapy and care I received at RoarWellness helped me regain control of my life.", imageUrl: "https://i.pravatar.cc/96?img=11" },
  { key: "facility-table-tennis", group: "facility", heading: "Table Tennis", eyebrow: "Facility", body: "A fun table setup for fast-paced ping pong matches that boost focus and energy.", imageUrl: "/images/facility-table-tennis.webp" },
  { key: "facility-pool", group: "facility", heading: "Swimming Pool", eyebrow: "Facility", body: "A clean pool for relaxation, rehab, and healthy aquatic exercise routines.", imageUrl: "/images/facility-swimming-pool.webp" },
  { key: "facility-gym", group: "facility", heading: "Gym", eyebrow: "Facility", body: "Modern gym equipment to support strength, stamina, and self-confidence.", imageUrl: "/images/facility-gym.webp" },
  { key: "facility-therapy-room", group: "facility", heading: "Medical Room", eyebrow: "Facility", body: "Fully facilitated medical room for good mental peace and personal growth.", imageUrl: "/images/facility-therapy-room.webp" },
  { key: "facility-yoga", group: "facility", heading: "Yoga Meditation", eyebrow: "Facility", body: "Peaceful yoga hall to regain balance, flexibility, and inner calm.", imageUrl: "/images/facility-yoga-meditation.webp" },
  { key: "facility-library", group: "facility", heading: "Library", eyebrow: "Facility", body: "Best library for reading and discussion for individual growth.", imageUrl: "/images/facility-library.webp" },
  { key: "facility-open-space", group: "facility", heading: "Open Space", eyebrow: "Facility", body: "Relax or walk in fresh air, reconnect with nature in our lush open ground.", imageUrl: "/images/facility-open-space.webp" },
  { key: "facility-snooker-table", group: "facility", heading: "Snooker Table", eyebrow: "Facility", body: "Play your game! Professional snooker table for mind-sharpening fun.", imageUrl: "/images/facility-snooker-table.webp" },
  { key: "approach-evidence", group: "approach", heading: "Evidence based therapy", eyebrow: "Approach", body: "Emotional Brain Training helps individuals rewire stress responses, develop emotional regulation, and shift from negative patterns to healthier thinking and behavior patterns.", imageUrl: "https://images.unsplash.com/photo-1576091160550-2173dba999ef?auto=format&fit=crop&w=1200&q=80" },
  { key: "approach-detox", group: "approach", heading: "Dynamic Detox", eyebrow: "Approach", body: "This method uses natural techniques like hydration, diet, and movement to remove toxins, cleanse the system, and renew physical and mental clarity safely and holistically.", imageUrl: "https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1200&q=80" },
  { key: "approach-yoga", group: "approach", heading: "Yoga", eyebrow: "Approach", body: "Yoga enhances mind-body awareness, reduces anxiety, and improves physical strength and flexibility through poses, breathwork, and meditation, fostering complete well-being.", imageUrl: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&w=1200&q=80" },
  { key: "approach-game-therapy", group: "approach", heading: "Game Therapy", eyebrow: "Approach", body: "Game Therapy uses structured play to promote communication, boost self-esteem, manage behaviors, and encourage recovery in an engaging and enjoyable format.", imageUrl: "https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=1200&q=80" },
  { key: "approach-art-therapy", group: "approach", heading: "Art Therapy", eyebrow: "Approach", body: "Art Therapy provides a non-verbal outlet for expressing emotions and trauma, aiding in emotional release, self-discovery, and the healing process through creative means.", imageUrl: "https://images.unsplash.com/photo-1517048676732-d65bc937f952?auto=format&fit=crop&w=1200&q=80" },
  { key: "approach-water-sports", group: "approach", heading: "Water Sports", eyebrow: "Approach", body: "Water activities such as swimming and kayaking help build confidence, improve fitness, and provide therapeutic relaxation that supports emotional and physical recovery.", imageUrl: "https://images.unsplash.com/photo-1530549387789-4c1017266635?auto=format&fit=crop&w=1200&q=80" },
  { key: "approach-psychology", group: "approach", heading: "Psychology", eyebrow: "Approach", body: "Psychological counseling helps individuals understand emotions, change negative thinking patterns, and heal past trauma through therapeutic dialogues and behavior strategies.", imageUrl: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=1200&q=80" },
];
